-- Define a recursive Common Table Expression (CTE) named 'pattern' with a single column 'n'
WITH RECURSIVE pattern(n) AS (  
    SELECT 20                    -- Sets the initial value of n to 20. This means the first row will have a value of 20. Can also be set as 'SELECT 20 AS "n"'.
    UNION                        -- Combine results from the initial SELECT with the recursive SELECT
    SELECT n - 1                 -- Decrease the value of 'n' by 1 for the next recursive call
    FROM pattern                 -- Reference the 'pattern' CTE to continue generating values
    WHERE n > 1                  -- Continue the recursion as long as 'n' is greater than 1
)
SELECT REPEAT('* ', n) AS "Stars" -- For each value of 'n' generated by the CTE, repeat the '*' character 'n' times
FROM pattern;                     -- Select from the 'pattern' CTE to produce the final output
